### ISSUE TITLE
Fallback: Exceptions are wrapped in FailsafeException

### ISSUE THREAD

**Issue by alexsanzdev** [jhalterman/failsafe#48] opened 2016-08-10 08:54 UTC
Hi, my usecase is that I want to throw my own custom exception as a fallback:

``` java
Failsafe.with(retryPolicy)
   .withFallback(new CheckedConsumer<Throwable>() {
       @Override
       public void accept(Throwable throwable) throws Exception {
           throw new MyCustomException(throwable);
       }
   })
   .get(...);
```

The issue is that whenever I use any of the checked functional interfaces, my custom exception gets wrapped in a `FailsafeException`. Only when I use a non-checked functional interface like `Callable` my custom exception is thrown unwrapped. The problem with using `Callable` is that I no longer get access to the failure (`Throwable`), and I want to wrap the failure in my custom exception, like in my example code above.

Thanks in advance, and thanks for a great library.

**Comment by jhalterman** [comment] 2016-08-10 16:57
Without doing a sneaky throws (which I'd prefer not to do), the only way for Failsafe to throw checked exceptions is to wrap them in `FailsafeException`. So for the sake of consistency, the intended behavior is to wrap all failures in FailsafeException, similar to how the executors framework wraps asynchronous failures in `ExecutionException`. Hopefully that works for you?

As for this behavior:

> Only when I use a non-checked functional interface like Callable my custom exception is thrown unwrapped

...I'm not able to reproduce it. Can you share a little test or reproducer?

**Comment by jhalterman** [comment] 2016-11-18 04:25
A change was just made via issue #66 where **only** checked exceptions are wrapped in `FailsafeException` now. So in your example, `MyCustomException` will only be wrapped if it's a checked exception. Hopefully this helps. 

Closing for now unless you're still hitting any problems related to this, then feel free to reopen.

**Closed by jhalterman** 2016-11-18 04:25 UTC
Labels: more info needed

**Comment by alexsanzdev** [comment] 2016-12-07 13:22
Great! thanks!

**Comment by IevgenRagulin** [comment] 2023-08-17 15:31
Hm... FailsafeException isn't a checked exception though. Is there a way to make Failsafe throw a checked exception?

**Comment by jhalterman** [comment] 2023-08-17 15:34
@IevgenRagulin The drawback of making `FailsafeException` checked is that calling code would be forced to handle it, which is not great. An alternative would be to use the [sneaky throws](https://www.baeldung.com/java-sneaky-throws) technique to forcefully throw checked exceptions, but that also has drawbacks. This is why Failsafe uses the current approach of wrapping checked exceptions in an unchecked `FailsafeException`.

**Comment by IevgenRagulin** [comment] 2023-08-17 15:52
@jhalterman, forcing the code to handle the exception is exactly why I would like to use a forced exception. Changing the type of the exception that was thrown prior to retries feels unintuitive. If the code has thrown an SQLException, this is what I believe Failsafe should rethrow (it's probably ok if it's wrapped in a FailsafeException, but it would be great if at least the type - checked vs unchecked remained the same)

**Comment by jhalterman** [comment] 2023-08-17 16:02
Thanks @IevgenRagulin. While some users might prefer to have checked exceptions thrown (ex: `run(CheckedSupplier<T>) throws E`), most users probably do not want to have to handle checked exceptions and/or aren't using them in their Failsafe executions. And unfortunately we had to choose one approach or the other, so we chose to wrap.

**Comment by Tembrel** [comment] 2023-08-17 16:14
It would have made the API much more complicated, too.

You could create your own utility method around the Failsafe call to unwrap your custom exception, e.g., something like this (uncompiled, untested):
```java
public class CustomFailsafe {
    public static <R> R customGet(FailsafeExecutor<R> exec, CheckedSupplier<R> supplier) throws MyCustomException {
        try {
            return exec.get(supplier);
        } catch (FailsafeException ex) {
            Throwable cause = ex.getCause();
            if (cause instanceof MyCustomException)
                throw cause;
            throw ex;
        }
    } 
}
```

**Comment by IevgenRagulin** [comment] 2023-08-17 16:16
@Tembrel love it, thank you, I think that's what I will do
