### ISSUE TITLE
Storage of CircuitBreakers

### ISSUE THREAD

**Issue by johnament** [jhalterman/failsafe#100] opened 2017-07-05 18:04 UTC
While integrating Failsafe with an application, I noticed that if I didn't keep track of my CircuitBreakers, the circuits never failed.  It would be good if Failsafe could keep track of my CircuitBreakers for me, maybe in a persistent or transient way.

**Comment by jhalterman** [comment] 2017-07-05 18:22
@johnament Do you mean if you use a new CircuitBreaker on each execution it would never fail? You're right that managing CircuitBreakers (and RetryPolicies, FWIW), is not done by Failsafe. I've considered adding a simple registry capability for these things, but my thinking was that they're best managed by users themselves, who may be using DI containers to lookup/inject/etc CircuitBreakers or RetryPolicies by name, or whatever else.

**Comment by MALPI** [comment] 2017-07-16 18:32
@johnament Maybe check if [Failsafe-Actuator](https://github.com/zalando-incubator/failsafe-actuator) fits your needs? It should, if you are using spring.

**Comment by whiskeysierra** [comment] 2018-07-12 22:56
Since last year we slightly changed the focus of [failsafe-actuator](https://github.com/zalando-incubator/failsafe-actuator). Its sole purpose is to expose `/acutator/circuit-breakers` which allows monitoring as well as management (state changing) of all circuit breakers within Spring's application context. The endpoint just picks up all circuit breakers that it finds.

We moved the configuration part over to [Riptide: Spring Boot Starter](https://github.com/zalando/riptide/tree/master/riptide-spring-boot-starter). Circuit breakers can be configured as part of our client configuration (base url, timeouts, retries, etc.). In the end all circuit breakers are just ordinary beans within the application context.

**Comment by jhalterman** [comment] 2018-12-28 07:06
@johnament Was re-visiting this, and a few thoughts:

> I noticed that if I didn't keep track of my CircuitBreakers, the circuits never failed

That sounds like a bug, though I wasn't able to reproduce this. Do you have a small reproducer if this is still happening/relevant?

> It would be good if Failsafe could keep track of my CircuitBreakers for me

Failsafe 2 (coming soon) will allow arbitrarily composable policies, where the Failsafe class itself is just an ordered set of policies to apply to executions:

```java
Failsafe failsafe = Failsafe.with(fallback, retryPolicy, circuitBreaker).
failsafe.run(this::connect);
```

We could expose the internal policies that a Failsafe instance maintains:

```java
List<Policy> policies = failsafe.getPolicies();
```

...but I'm not sure if that's exactly what you're after since you'd need to pick through them to find the CircuitBreaker, if any.

It's worth noting that Failsafe 2 will allow multiple instances of the same policy, for example, multiple CircuitBreakers, if for example, you wanted different CircuitBreakers to handle different failures that might occur on the same execution.

**Comment by jhalterman** [comment] 2019-01-14 03:49
Closing for now.

**Closed** 2019-01-14 03:48 UTC
